sonar.projectKey=lnx85_delios
sonar.organization=lnx85

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Delios

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./custom_components/delios
sonar.branch.name=main
sonar.tests=./tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Extra settings
sonar.python.coverage.reportPaths=/github/workspace/coverage.xml
sonar.python.version=3.13
